export const GET_MENUS = 'GET_MENUS'
export const ADD_ORDER = 'ADD_ORDER'
export const DELETE_ORDER = 'DELETE_ORDER'
export const GET_ORDERS = 'GET_ORDERS'
export const ORDER_QTY = 'ORDER_QTY'
export const POST_ORDER = 'POST_ORDER'
export const GET_BILL = 'GET_BILL'